### ISSUE TITLE
Shadowing of index.md in the demo does not work

### ISSUE THREAD

**Issue by fkromer** [NK-WebDev/gatsby-theme-teranova#11]

**Comment by nirjan-dev** [comment]
@fkromer Can you check again if changing index.mdx in the original location works for you? I checked it by commenting it out like this -
```mdx
{/* <Contact /> */}
```
which did not work but when I did it like this -
```mdx
<!--  <Contact /> -->
```
it works and other changes made to that file are also working.
I also had to add an index.mdx to src/pages to make sure an index.html file is created after the build command, removing this will create a public folder without the html file

**Comment by fkromer** [comment]
@NK-WebDev If I comment sections out in `demo/src/gatsby-theme-teranova/pages/index.mdx` (syntax does not matter) and run the demo `demo$ gatsby develop` the section is still shown. Seems like it is taken from the theme's builtin code.
