### ISSUE TITLE
Improve theme adaptability

### ISSUE THREAD

**Issue by fkromer** [NK-WebDev/gatsby-theme-teranova#17]
In case a user wants to modify the theme she could do so by overriding files `about.js`, `contact.js`, `contactinfo.js`, etc. in her site or custom demo via pasting them into `custom-demo/src/gatsby-theme-teranova/components`. However many component files reference other component files via `import xxx from './<path>'` style imports. Could we change them to `import xxx from 'gatsby-theme-teranova/src/components/<path>`. This would ease adaptability and people would have an easier time contributing to your theme.

**Comment by nirjan-dev** [comment]
Yeah I think that will be better, @fkromer Have you done those type of relative imports in gatsby before? I have done it in angular but I might need to do some research on how to achieve this in gatsby.

**Comment by nirjan-dev** [comment]
I initially thought this would break shadowing but turns out everything works fine so I just updated all the relative imports into absolute imports. Now, just by copying the files shadowing should work right away.

**Comment by fkromer** [comment]
@NK-WevDev Great! Thanks a lot.
