### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by fkromer** [NK-WebDev/gatsby-theme-teranova#2]
You project misses a license file. Could you add one please? For guidance about how to choose an open-source license refer to e.g. here [https://choosealicense.com/](https://choosealicense.com/) ([license overview](https://choosealicense.com/licenses/)).

**Comment by nirjan-dev** [comment]
Thanks for mentioning this, A MIT LICENSE is now added to the project.

**Comment by fkromer** [comment]
The [`package.json`](https://docs.npmjs.com/creating-a-package-json-file#example-1) is missing the license as well :wink:

**Comment by nirjan-dev** [comment]
Just added the license to the package.json as well.
