### ISSUE TITLE
How to shadow builtin demo webpage content?

### ISSUE THREAD

**Issue by fkromer** [NK-WebDev/gatsby-theme-teranova#3]
I thought the textual content of a theme webpage is defined in `*.mdx` files (`gatsby-theme-teranova/data/content/about.mdx`, `gatsby-theme-teranova/data/content/contact.mdx`, etc.) and is rendered with corresponding `*.js` files of the theme (`gatsby-theme-teranova/src/components/about.js`, `gatsby-theme-teranova/src/components/contact.js`, etc.). There is just `demo/src/pages/index.mdx` in the demo. Means the theme buildin content is not modified in the demo. I expected that placing custom text content in `demo/data/gatsby-theme-teranova/content/about.mdx, etc.` would shadow the corresponding webpage content. At least this seems to be the way how shadowing usually works according to the [docs](https://www.gatsbyjs.org/docs/themes/shadowing/#customizing-the-bio-component). But when running `gatsby develop` the custom text is not shown. The shadowed file seems to be just ignored. How is done shadowing of the webpage text correctly?

**Comment by fkromer** [comment]
It turned out that instructions in the README.md are not correct and that shadowing is not fully supported yet. Refer to https://github.com/NK-WebDev/gatsby-theme-teranova/issues/9 for the current state of fixes.

**Comment by fkromer** [comment]
The content of e.g. `intro.mdx` should be shadowed when overriding ` demo/data/gatsby-theme-teranova/content/intro.mdx` like in https://github.com/fkromer/gatsby-theme-teranova/tree/shadow-index-mdx. However it's not working.

**Comment by nirjan-dev** [comment]
I've been sick for a couple of days and now I have some work to catch up on so I'll probably be able to look at this issue by the end week but not right now.

**Comment by fkromer** [comment]
Thanks. Would be great. I had no time to look into this yet.

**Comment by nirjan-dev** [comment]
fixed in version 2.0.0
