### ISSUE TITLE
Shadowing of index.js has no effect

### ISSUE THREAD

**Issue by fkromer** [NK-WebDev/gatsby-theme-teranova#7]
During usage of the theme (e.g. in the demo) when overriding `index.js` via `demo/src/gatsby-theme-teranova/data/index.js` the customization is just ignored (`gatsby develop`).

**Comment by fkromer** [comment]
Use sitemeta in gatsby-config.js instead. Demo code fixed with https://github.com/NK-WebDev/gatsby-theme-teranova/pull/15

**Comment by nirjan-dev** [comment]
Merged #15
